universe = vanilla

executable = /eos/home-a/arnaik/Skimmer_HtoAAto4g/condor_jobs_skimmer/run_single_file.sh
arguments = $(job_idx)

x509userproxy = /tmp/x509up_u186038
use_x509userproxy = True
transfer_input_files = /tmp/x509up_u186038

notification = never
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
MY.OutputDestination = "root://eosuser.cern.ch//eos/user/a/arnaik/Sergi_evtmixed_Skimmed_noCuts"
getenv = True

request_memory = 5000MB
request_cpus = 1

+JobFlavour = "nextweek"

log = /eos/home-a/arnaik/Skimmer_HtoAAto4g/condor_jobs_skimmer/logs/$(Cluster).log

queue job_idx from /eos/home-a/arnaik/Skimmer_HtoAAto4g/condor_jobs_skimmer/jobs.txt
